title: कादम्बरी (K-11)
author: बाणभट्टः
type: kavya-prose
chapters: अनुक्रमणिका
order: 1
gloss_types:
  - data_type: notes
    css_style: fine_print
    hideable: true
    hidden_by_default: false
header: |
  **रजोजुषे जन्मनि सत्ववृत्तये स्थितौ प्रजानां प्रलये तमःस्पृशे ।<br>
  अजाय सर्गस्थितिनाशहेतवे त्रयीमयाय त्रिगुणात्मने नमः ॥**<br>
