title: उत्तररामचरितम्
author: भवभूतिः
chapters: अङ्काः
ignore: false
default_class: dialog-block
default_shloka_type: nataka
order: 3
header: |
  **इदं कविभ्यः पूर्वेभ्यो नमोवाकं प्रशास्महे ।<br>
  वन्देमहि च तां वाणीममृतामात्मनः कलाम् ॥**<br>
