title: किरातार्जुनीयम्
author: भारवी
type: kavya-verse
chapters: सर्गाः
dict-skip: [वा, न, तेन, के, अपि, माम्, मम, मां, त्वम्, त्वं, एष्, एव, इति, च, कुरु, किं, परं, फलम्, मनो, मनः, नैव, जप, परम्, कर्म, क, को, का, स]
