title: कुमारसम्भवम्
author: कालिदासः
type: kavya-verse
chapters: सर्गाः
order: 2
header: |
  **अस्त्युत्तरस्यां दिशि देवतात्मा हिमालयो नाम नगाधिराजः ।<br>
  पूर्वापरौ तोयनिधी वगाह्य स्थितः पृथिव्या इव मानदण्डः ॥**<br>
