title: रसगङ्गाधरः (Sah-31)
author: पण्डितजगन्नाथः
type: shastra-vada
chapters: आननानि
default_class: vritti
default_shloka_type: karika
order: 3
gloss_types:
  - data_type: notes
    css_style: fine_print
    hideable: true
    hidden_by_default: false
