title: रसगङ्गाधरः (Sah-31)
author: पण्डितजगन्नाथः
type: shastra-vada
chapters: आननानि
default_class: vritti
default_shloka_type: karika
order: 3
gloss_types:
  - data_type: notes
    css_style: fine_print
    hideable: true
    hidden_by_default: false
header: |
  **स्मृताऽपि तरुणातपं करुणया हरन्ती नृणाम्<br>
  अभङ्गुरतनुत्विषां वलयिता शतैर्विद्युताम्।<br>
  कलिन्दगिरिनन्दिनीतटसुरद्रुमालम्बिनी<br>
  मदीयमतिचुम्बिनी भवतु काऽपि कादम्बिनी॥**<br>
