chapter_name: "उत्तरमेघः"
dict:
   title: "[उत्तरमेघः]"
   type: shloka
   skip: [वा, न, तेन, के, अपि, माम्, मम, मां, त्वम्, त्वं, एष्, एव, इति, च, कुरु, किं, परं, फलम्, मनो, मनः, नैव, जप, परम्, कर्म, क, को, का, स]
   chapter_key: MD-2
   shloka_key_prefix: "MD,9,00"
