title: मेघदूतम्
author: कालिदासः
type: kavya-verse
chapters: भागाः
order: 3
header: |
  <br>
  **कश्चित्कान्ताविरहगुरुणा स्वाधिकारात्प्रमत्तः<br>
  शापेनास्तङ्गमितमहिमा वर्षभोग्येण भर्तुः ।<br>
  यक्षश्चक्रे जनकतनयास्नानपुण्योदकेषु<br>
  स्निग्धच्छायातरुषु वसतिं रामगिर्याश्रमेषु ॥**<br>
  <audio controls>
      <source src="/assets/audio/chandas/mandakranta-r-megha1.mp3" type="audio/mpeg">
          Your browser does not support the audio element.
  </audio>

