title: स्वप्नवासवदत्तम्
author: भासः
type: kavya-play
chapters: अङ्काः
ignore: false
default_class: dialog-block
default_shloka_type: nataka
order: 1
header: |
  **उदयनवेन्दुसवर्णावासवदत्ताबलौ बलस्य त्वाम् ।<br>
  पद्मावतीर्णपूर्णौ वसन्तकम्रौ भुजौ पाताम् ॥**<br>
