title: किरातार्जुनीयम्
author: भारवी
chapters: सर्गाः
order: 3
source: "01 - ocr/typed; 02 - sanskritsahitya.org"
dict:
   folder: "kavya"
header: |
  **श्रियः कुरूणामधिपस्य पालनीं प्रजासु वृत्तिं यमयुङ्क्त वेदितुम् ।<br>
  स वर्णिलिङ्गी विदितः समाययौ युधिष्ठिरं द्वैतवने वनेचरः ॥**<br>
