title: काव्यप्रकाशः (Sah-47)
author: मम्मटः
type: shastra-karika
chapters: उल्लासाः
default_shloka_type: karika
default_class: vritti
order: 1
gloss_types:
  - data_type: notes
    css_style: fine_print
    hideable: true
    hidden_by_default: false
header: |
  **नियतिकृतनियमरहितां ह्लादैकमयीमनन्यपरतन्त्राम्।<br>
  नवरसरुचिरां निर्मितिमादधती भारती कवेर्जयति ॥१॥**<br>
